### PR TITLE
[Enhancement] Implemented identity feature

### PR DESCRIPTION
**Pull request by St4NNi**
This is my naive approach / suggestion to solve #16. The PR adds a public struct: `Identity`  to `ops/mod.rs: 305`:

```rust
#[derive(Debug, Default)]
pub struct Identity {
    pub access_key: String,
    pub secret_key: String,
}
```

This struct contains the owned values for `access_key` and `secret_key` that are used for signature verification and passes them through `prepare` and `call` to all methods of the `s3_trait`. With this change it will be possible to use the users identity in upstream logic and associate corresponding backend actions to a specific user, enabling custom user management. 

Example of the additions to the methods from the `s3_trait`:

```diff
async fn abort_multipart_upload(
    &self,
    _input: AbortMultipartUploadInput,
+    _identity: Identity,
) -> S3Result<AbortMultipartUploadOutput> {
    Err(s3_error!(NotImplemented, "AbortMultipartUpload is not implemented yet"))
}
```

These additions do not change anything related to the actual signature verification logic and are optional to be used by the implementer. 

Feel free to make suggestions / enhancements when this change does not fit in your plans. If these changes are accepted they should surely result in a new release since they changed the method signatures in the s3_trait.

---

*By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.*

### CODE REVIEW

**Comment by Nugine** [comment]
Thank you! But I think the issue needs a better solution.

My draft:

`s3s` can implement a type like [aws_credential_types::Credentials](https://docs.rs/aws-credential-types/latest/aws_credential_types/struct.Credentials.html). 

```rust
pub struct S3Request<T> {
    pub input: T, // operation input
    pub credentials: Option<Credentials>, // identity information. `None` for anonymous request
    pub extensions: http::Extensions, // forward extensions from the http request
    ...
}
```

```diff
async fn abort_multipart_upload(
    &self,
-   _input: AbortMultipartUploadInput,
+   _req: S3Request<AbortMultipartUploadInput>,
) -> S3Result<AbortMultipartUploadOutput> {
    Err(s3_error!(NotImplemented, "AbortMultipartUpload is not implemented yet"))
}
```

**Comment by St4NNi** [comment]
Yeah, as i've said my approach was more of a hacky prototype solution than a fully fletched out one. Your draft sounds much more ergonomic, if you'd like i could give it a try.

**Comment by Nugine** [comment]
Finished in commit 4039538daf2366c13d19e0cad3c962cf18b1b507. It's a big refactor so I implemented by myself.

**Comment by St4NNi** [comment]
Very nice, thanks a lot ! This will make our work a lot easier.

**Pull request closed without merging**
