### PR TITLE
Upgrade model and aws sdk

### LINKED ISSUE #100: aws breaking changes 20231102
+ https://github.com/awslabs/aws-sdk-rust/blob/main/CHANGELOG.md#november-2nd-2023
+ https://github.com/awslabs/smithy-rs/blob/main/CHANGELOG.md#november-1st-2023
+ https://github.com/Nugine/s3s/pull/99

#100, #107, #111 

+ [ ] update to the latest smithy model and adjust codegen
+ [ ] update to aws sdk 1.0
+ [ ] update to hyper 1.0

### LINKED ISSUE #111: aws sdk rust 1.0
https://aws.amazon.com/cn/blogs/developer/announcing-general-availability-of-the-aws-sdk-for-rust/

+ https://github.com/awslabs/aws-sdk-rust/blob/main/CHANGELOG.md#november-24th-2023
+ #100

### PR DESCRIPTION
**Pull request by Nugine**
resolves #100
resolves #111 

Some notes:
+ https://github.com/smithy-lang/smithy-rs/discussions/3022

### CODE REVIEW

**Comment by prathmesh-kallurkar** [comment]
Hi Nugine

When are you planning to merge this code in to mainline? This commit is super useful for users who rely on the repository and want to upgrade their SDK dependency to 1.X.

**Comment by houqp** [comment]
@Nugine let us know if there is anything we can help to get this over the finish line.

**Comment by Nugine** [comment]
The next release v0.9.0 is scheduled for Mar 9th.
This version contains lots of breaking changes introduced by the latest smithy model. You can test it via git dependency before the release date. Report any problem :)
If we encounter any major issue, the release will be postponed until we fix it.

**Comment by St4NNi** [comment]
Thanks a lot @Nugine. Will this also include the Hyper 1.0 upgrade? We are waiting for that as well and might try it after that.

**Comment by Nugine** [comment]
> Thanks a lot @Nugine. Will this also include the Hyper 1.0 upgrade? We are waiting for that as well and might try it after that.

See #107. It's still blocking. We have to wait for aws sdk upgrade.

**Pull request merged**
